---
driver:
  name: vagrant
  customize:
    memory: 2048
driver_config:
 require_chef_omnibus: latest

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3
suites:
  - name: manager-development
    driver:
      network:
      - ["private_network", {ip: "172.16.10.10"}]
    run_list:
      - recipe[wazuh::default]
      - recipe[wazuh::manager]
      - recipe[wazuh::wazuh-api]
      - recipe[wazuh_filebeat::default]
  - name: elk-1
    driver:
      network:
      - ["private_network", {ip: "172.16.10.11"}]
    run_list:
      - recipe[wazuh_el::default]
      - recipe[wazuh_el::java]
      - recipe[wazuh_el::elasticsearch]
  - name: elk-2
    driver:
      network:
      - ["private_network", {ip: "172.16.10.12"}]
    run_list:
      - recipe[wazuh_el::default]
      - recipe[wazuh_el::java]
      - recipe[wazuh_el::elasticsearch]
  - name: elk-3
    driver:
      network:
      - ["private_network", {ip: "172.16.10.13"}]
    run_list:
      - recipe[wazuh_el::default]
      - recipe[wazuh_el::java]
      - recipe[wazuh_el::elasticsearch]
